# This mimics the script that Xcode Cloud will call for the Staging and Production builds. It will pass in the proper environment variable parameters to copy_environment_vars.sh (see ci-scripts/ci_pre_xcodebuild.sh).
# Use this script for locally populating the entitlements and Info.plist files with Merchant IDs, API Keys, etc.
# From root directory, call with:
# ./scripts/copy_local_environment_vars.sh "{"Weekly Staging Build" or "Wikipedia Experimental PR Build" or "Nightly Build"}" "{merchant-ID-here}" "{payments-API-key-here}"

# Do not commit the changes generated by this script.

if [ $# -eq 0 ];
then
  echo "$0: Missing arguments"
  exit 1
elif [ $# -gt 4 ];
then
  echo "$0: Too many arguments: $@"
  exit 1
fi

Workflow=$1
MerchantID=$2
PaymentsAPIKey=$3

EntitlementsFile="Wikipedia/Wikipedia.entitlements"

if [[ ${Workflow} == "Weekly Staging Build" ]]; then
    InfoPListFile="Wikipedia/Staging-Info.plist"
    ./ci_scripts/copy_environment_vars.sh $EntitlementsFile $InfoPListFile $MerchantID $PaymentsAPIKey
    
elif [[ ${Workflow} == "Wikipedia Experimental PR Build" ]]; then
    InfoPListFile="Wikipedia/Experimental-Info.plist"
        ./ci_scripts/copy_environment_vars.sh $EntitlementsFile $InfoPListFile $MerchantID $PaymentsAPIKey

elif [[ ${Workflow} == "Nightly Build" ]]; then
    InfoPListFile="Wikipedia/Wikipedia-Info.plist"
    ./ci_scripts/copy_environment_vars.sh $EntitlementsFile $InfoPListFile $MerchantID $PaymentsAPIKey
fi
